### ISSUE TITLE
Create data provider events

### ISSUE THREAD

**Issue by three** [HackRU/sledge#22]
Implement the data provider methods in react-admin. This would replace `REQUEST_GET_OBJECTS`. Data should be passed pretty much directly from react-admin.

https://marmelab.com/react-admin/DataProviders.html

**Comment by three** [comment]
@ColeFrench How's progress on this?

**Comment by ColeFrench** [comment]
I just pushed a commit, 664285cae242717506c4c89569a7f4c54634f68f. This implements `getList` *almost* as desired. What I'm going to do next is replace this list of valid tables https://github.com/HackRU/sledge/blob/664285cae242717506c4c89569a7f4c54634f68f/src/server/GetObjectsRequest.ts#L41-L49 with a dynamic check for an `id` column, which is all that is needed for the database query to work.

Also, I'm confused on the usage of `simpleValidate`. It looks like it is not being called. Is there an optional setting that has to be provided to sledge to validate requests? I need some way to validate request parameters before I use them to query the database (so that the server doesn't crash with an error from an invalid query). Should I then just call `simpleValidate` inside `handleSync`?

**Comment by three** [comment]
I think not calling validate is a bug in `EventHandler.ts`. I might have removed the check during another PR, but I'll try to fix it and add some tests so it doesn't happen again. One comment is the validate should probably all be in validator. You should be able to use `tc.oneOf([tc.isConstant(...), ...])` but otherwise the validate stuff looks good.

**Comment by three** [comment]
Can you create a draft PR for this?
